### ISSUE TITLE
GPG Key Variable

### ISSUE THREAD

**Issue by Dumbaz** [pcfens/puppet-filebeat#132]
I cannot freely access the internet from my servers, which makes the $yum_repo_url variable really useful, as I can change it to the local repository mirror. The GPGkey however is set to "https://artifacts.elastic.co/GPG-KEY-elasticsearch". I can change the values by hand, but a variable for it would be very useful.

from `repo.pp`:
```
$yum_repo_url = 'https://artifacts.elastic.co/packages/5.x/yum'
baseurl  => $yum_repo_url,
gpgkey   => 'https://artifacts.elastic.co/GPG-KEY-elasticsearch',
```

**Comment by pcfens** [comment]
I'll put something like this on the todo list. I'd like to let the repository URL and key URL both be set as input parameters to the `filebeat` class instead of having to modify the private `filebeat::repo` class.

In the interim, I'd suggest setting `manage_repo` to false in your `::filebeat` declaration and manually adding the `yumrepo` resource:
```puppet
yumrepo { 'beats':
  ensure   => present,
  descr    => 'elastic beats repo',
  baseurl  => 'https://artifacts.elastic.co/packages/5.x/yum',
  gpgcheck => 1,
  gpgkey   => 'https://artifacts.elastic.co/GPG-KEY-elasticsearch',
  enabled  => 1,
}
```

**Comment by pcfens** [comment]
I'm going to close this since I haven't gotten to it in this long. If anyone is having trouble getting this module to use an externally managed repository please let me know and I'll try to help.
