### ISSUE TITLE
issue with version 2.3.0

### ISSUE THREAD

**Issue by amitdaniel86** [pcfens/puppet-filebeat#144]
Hi . 

I tried to use the new version and i'm getting an error : 

Error: Syntax error at 'String'; expected ')' /modules/filebeat/manifests/init.pp:48

Any idea what is the issue ?
the previous version i used is : 0.11.1

thanks , 
Amit

**Comment by amitdaniel86** [comment]
@pcfens i'm using : puppet-3.8.7
Actually we can't upgrade the puppet to v.4.0 but is that possible for you to release a hotfix with my PR to an older version ?

i'm using 0.11.1 version for your module .

**Comment by pcfens** [comment]
I'd prefer to avoid officially supporting software that hasn't had a security update in over a year, and I don't know of a way to release a version to the forge out of sequence, so I won't be releasing anything that I'm willing to support, so I'm going to close the issue, but hopefully offer a resolution:

After checking out the last version that supported Puppet 3 (v1.0.0), I was able to cherry pick your commit (f38bb37) without any merge conflicts. I'd suggest forking this repository and creating a new branch where you can backport and modify the module as needed.

You can point your Puppetfile at your public or private fork and branch to keep the deploy process the same as modules from the forge (feel free to reply if I can help with that part of the process).

**Comment by pcfens** [comment]
I should have also mentioned that you can tell this module to use a custom template with the `conf_template` parameter. The module itself doesn't validate many parameters, so you may be able to drop the modified template somewhere in your control repo and tell the old version of the module you're currently using to use that template. Either fix will have the same result since there aren't any other updates supporting Puppet 3.

**Comment by amitdaniel86** [comment]
@pcfens AWESOME !
I used the conf_template with custom template and it's working just fine .

Thanks !
