### ISSUE TITLE
Unable to upgrade to filebeat version 5.6

### ISSUE THREAD

**Issue by ob2** [pcfens/puppet-filebeat#151]
Howdy, I don't seem to be able to set/keep my filebeat version to 5.6 even though the major version has been set to 5: 

filebeat::major_version: '5'

I was able to upgrade to v5.6, yet somehow it automatically updated to v6.1

--Snip!--
Jan 18 14:49:25 Updated: filebeat-5.6.6-1.x86_64
Jan 19 03:51:13 Updated: filebeat.x86_64 6.1.2-
--End!--

Beats.repo seems a bit buggy:

--Snip!--
[beats]
name=Elastic repository for 5.x packages
baseurl=https://artifacts.elastic.co/packages/6.x/yum
enabled=1
gpgcheck=1
gpgkey=https://artifacts.elastic.co/GPG-KEY-elasticsearch
--End!--

The base name and url don't seem to match..

How do I get the above to stick to the 5.6 version?

**Comment by pcfens** [comment]
What version of the module and puppet are you using? I don't know that it will matter, but it may help rule out some possible causes.

**Comment by ob2** [comment]
Thanks for coming back to me. I am using module version '1.0.0' on Puppet 3.

**Comment by pcfens** [comment]
That's very weird - are you setting the value of `package_ensure`? I'm a little stumped as to why Puppet would be changing repository endpoint since that version of the module doesn't have any reference to the 6.x repository (or the name that's set in that snippet for that matter).

Perhaps the 5.6 package is modifying the repository info? Do subsequent puppet runs change anything back?

**Comment by pcfens** [comment]
I'm going to go ahead and close this since there hasn't been any activity. If you'd still like some help just comment and we can re-open.
