### ISSUE TITLE
offline installation of filebeat

### ISSUE THREAD

**Issue by ltutar** [pcfens/puppet-filebeat#19]
It would be nice to install the filebeat offline.

**Comment by pcfens** [comment]
Hi @ltutar - can you explain a little bit of what you mean by offline install? Are you thinking configuration only with filebeat already installed, a tarball/package already on the local system, or something else?

Knowing your specific use case might help a bit here.

**Comment by ltutar** [comment]
Hi Phil,
Something like 
```
jenkins::direct_download: 'puppet:///puppet_files/jenkins/jenkins_rpm/jenkins-1.655-1.1.noarch.rpm'
```
would be fine. 
1) The machines do not have internet connection.
2) I do not want to be dependent on IaaS guys in order to get the rpm in the local repo.

Thank you in advance.

**Comment by pcfens** [comment]
Using a repository is really the best way to do something like this - especially if a package is going to be used anyway. I've thought about adding support for the tarball downloads from elastic that might be extended to support something like this.

I'm a little concerned about shipping the RPM/DEB/tarball over puppet because
- Serving large files over puppet isn't typically considered best practice. These are probably small enough to still work without slowing down the server or agent though so this is a gray area.
- This module really wasn't designed with this use case in mind, and none of the remote file modules support talking to the puppet protocol, so there isn't a drop in fix.

I'll take a look and see what I can do, though PRs are always appreciated :smile:

**Comment by saikrishnagaddipati** [comment]
If someone wants to do an offline installation. Change the content in linux.pp folder to 
class filebeat::install::linux {
  package {'filebeat':
    source => 'rpm',
    ensure => $filebeat::package_ensure,
    source => 'give the path to your filebeat rpm file"
  }
}

**Comment by skyrawrcode** [comment]
Even being able to use chocolatey as a source would help with this.

**Comment by pcfens** [comment]
Chocolatey support is coming soon thanks to help in #237, but I don't see a case where I plan on supporting puppet as a file provider for the package, so I'm going to go ahead and close this (though I'd be open to a MR)
