### ISSUE TITLE
Adding topbeat and packetbeat to the same module

### ISSUE THREAD

**Issue by dasrecht** [pcfens/puppet-filebeat#2]
Hi there

First of all, thanks for the great work on this module. After trying the other modules which are out there for making filebeat work i found yours and it works splendid!

Because there's not just filebeat. I was thinking if it would make sense to have topbeat and packetbeat also in the same puppet module, because the configuration files are pretty similar and the repository where we install from is also the same.

What do you think about it?

Best,
/dasrecht

**Comment by pcfens** [comment]
Thanks for the idea. I haven't looked at the other *beat packages very closely at all, so I honestly don't know if ti makes sense or not.

My first reaction is to keep them as separate modules since each piece can standalone. At the very least we can use this module as a good starting point for the other *beats software. There may be some other ways within puppet we can reasonably pass the re-used information to each modules, but it really depends on what works best for each user.

Since I've only used filebeat there's a good chance I'm missing something simple, so please jump in to let me know what it is.

Thanks again!

**Comment by pcfens** [comment]
If anyone has any proposals of how the parameters would look to accomplish something like this, please chime in. I'm not opposed to integrating all 3 beats tools into one module, but since I don't use the others (yet), I'm not sure if it makes the most sense, or how to approach it if it does make sense.

**Comment by pcfens** [comment]
Rather than integrating these into this module I created [a topbeat module](https://github.com/pcfens/puppet-topbeat) based heavily on this one.

I'm going to close this for now, but will happily entertain PRs or proposals on sane ways to merge the various models.

**Comment by cdenneen** [comment]
@pcfens now that you have windows support in this module. would you be able to create similar to topbeat module, based on this, one for winlogbeats?

**Comment by pcfens** [comment]
I can create a module based on this one, but I'm not a Windows admin or dev by any stretch, so I'm a little hesitant to write code when I have no idea what best practices look like. The windows functionality we have in the filebeat module is thanks to @axier, not me.

If I get a chance to play with puppet in windows a little bit more I might try my hand at this one.
