### ISSUE TITLE
setting 'queue_size' has been removed

### ISSUE THREAD

**Issue by wortmanb** [pcfens/puppet-filebeat#200]
Using 3.3.3 with filebeats v6.5.1 I have encountered this error:
Error: Execution of "/usr/share/filebeat/bin/filebeat" -c "/etc/filebeat/filebeat.yml" test config' returned 1: Exiting: 1 error: setting 'queue_size' has been removed
Error: Failed to apply catalog: Cannot parse invalid user line: user   tags

Is there an easy way to tell the module to remove the queue_size setting short of modifying the template directly?

**Comment by wortmanb** [comment]
Removing the relevant lines from the template produces further errors. It looks like queue_size, filebeat.spool_size, filebeat.publish_async and filebeat.idle_timeout have all been removed.

**Comment by wortmanb** [comment]
Actually, this looks like a lot of filebeat's configuration has changed, including needing inputs defined in the main config(?).

Is it safe to assume you're looking at this already?

**Comment by pcfens** [comment]
I haven't looked at the queue_size stuff, but I've started work on the inputs piece in the [use_inputs](https://github.com/pcfens/puppet-filebeat/tree/use_inputs) branch (they can still be outside the main config file). Switching to using inputs will break the module for versions of filebeat prior to 6.3, so I don't want to push that change too early and break things for anyone (as I understand it, prospectors aren't being removed until v7).

Changing the configuration structure shouldn't be too hard to do since we're basically taking the config sections as hashes, combining them in to a larger hash, then rendering it as YAML. I haven't had a chance to spend a lot of time on this, but PRs are always welcome.

**Comment by wortmanb** [comment]
I'll take a look at the code and see if I can contribute in any meaningful way. :-)

**Comment by TuningYourCode** [comment]
we also had the problem because of "spool_size". Fix was to disable config test during the upgrade from pre 6 to version 6.
```
filebeat::disable_config_test: true
```
We will enable config test again after our nodes got upgraded to version 6.
