### ISSUE TITLE
validate_cmd on prospectors being used incorrectly

### ISSUE THREAD

**Issue by philomory** [pcfens/puppet-filebeat#201]
the `validate_cmd` attribute on a `file` resource is supposed to contain a command that will validate the new content _before_ it is put in place; generally speaking you pass a command that has a `%` as a placeholder for the path to the file being tested, and the puppet agent will write the file in `/tmp/`, run the `validate_cmd` (substituting `%` for the path to the file in `/tmp/`), and then, if the validation passes, it will place the file into its final location.

The `validate_cmd` attribute used in prospector.pp for version 5 is correct, but for any other version (that is, either 4 or 6), it is incorrect because it doesn't contain a `%` and so is just validating the live configuration. Further, since this is run _before_ the new configuration is put in place, it'll fail when trying to install the first prospector, since initially conf.d will be empty and `filebeat test config` will fail because no prospectors/inputs are defined.

**Comment by pcfens** [comment]
What's there is a little misleading - prospectors should probably have an undefined test for version 6.

Prospector config files can't be tested by themselves since they're only partial configs. The `test config` filebeat run option is testing for a full configuration file with inputs and outputs. Since there are no outputs in a single prospector/input, validation will always fail:
```bash
$ filebeat -c /etc/filebeat/conf.d/input.yml test config
Exiting: No outputs are defined. Please define one under the output section.
$ echo $?
1
```

I haven't had a lot of time to think about it in depth (work is on a long holiday break), but without a predictable test filename (or a wrapper script) I don't know of a good way to have Puppet test standalone input/prospector files.

Any ideas?

**Comment by philomory** [comment]
I mean, the main problem I have is that the current setup actually prevents deployment of a v6 configuration at all, if you don't already have a valid configuration in place. 

In theory, the following should work: `filebeat -E "filebeat.config.prospectors.path=%" test config`

However, it doesn't work. In testing to figure out why, it turns out that `filebeat config test` never validates prospector files in v6 at all; or rather, it validates that the files specified by `filebeat.config.{inputs,prospectors}.path` _exist_, but it doesn't care about their content at all. Even if you put absolute gibberish in a prospector file, the config test passes. It only fails if no prospector file exists at all.

This is probably worth filing a bug against filebeat for, but in the meantime the config test shouldn't be run for prospector files.

**Comment by philomory** [comment]
::sighs:: Sorry, disregard the part about preventing deployment of filebeat. The systems I was seeing that error on, were running an old version of the filebeat module somehow.
