### ISSUE TITLE
update filebeat to new version 

### ISSUE THREAD

**Issue by shreejit13** [pcfens/puppet-filebeat#21]
Is there a way to upgrade filebeat to new version in this module ?

**Comment by pcfens** [comment]
You should be able set the `package_ensure` parameter to the package version you'd like to install to update the installed package.

I'd suggest trying this in a vagrant/test system first just to make sure that your configuration still works like you expect.

If you run into issues let me know so that I can work on a fix.

**Comment by pcfens** [comment]
Hi @shreejit13 - were you able to upgrade filebeat this way?

**Comment by pcfens** [comment]
I'm going to go ahead and close this - if you're still having issues please feel free to comment and I'll re-open it.
