### ISSUE TITLE
Kibana host define 

### ISSUE THREAD

**Issue by devinmatte** [pcfens/puppet-filebeat#214]
Filebeat reaches out to Kibana to collect dashboards, allow defining a Kibana host so that this works

```
host: "http://kibana.example.com:5601"
```

**Comment by pcfens** [comment]
I think that this already works since it's in the [setup portion of the config](https://www.elastic.co/guide/en/beats/filebeat/current/setup-kibana-endpoint.html#_literal_setup_kibana_host_literal). You should be able to set this by doing something like
```puppet
class { '::filebeat':
  setup => {
    kibana => {
      host => 'kibana.example.com:5601',
    }
  }
}
```
You can also do something like
`setup::kibana::host: kibana.example.com:5601`
if you're using a yaml backend for hiera.

If you're looking for something else please let me know and I'll try to add it.

**Comment by devinmatte** [comment]
That worked! I'm still getting used to puppet, thanks!
