### ISSUE TITLE
Add Winlogbeat support

### ISSUE THREAD

**Issue by mightydok** [pcfens/puppet-filebeat#34]
Filebeat support only log files, but for windows eventlog there is winlogbeat program. Please add support for it in your module.

**Comment by pcfens** [comment]
I suspect that winlogbeat would be better suited by its own module instead of trying to have this module support 2 different log shippers for one OS. Perhaps rather than trying to add it here this module can be used as a framework of sorts for a new winlogbeats module.

There's certainly someone more qualified than me to maintain a module focused on windows (I'm exclusively in *nix land these days), though I'm happy to help however I can.

**Comment by mightydok** [comment]
Ok, i will try soon.
