### ISSUE TITLE
Assign a puppet manifest to a group host 

### ISSUE THREAD

**Issue by WILEC2** [pcfens/puppet-filebeat#37]
**Question

I have a puppet running with a Foreman node to manage different hosts. 

I installed and loaded puppet-filebeat with success and have access to class parameters in my Foreman web interface. I can assign different values to my parameters and assign the module to a host group to test and eventually to production host group to deploy.

The problem is I want to manage my SSL certificate so I created a manifest that looks like the one in the Wiki and created a mount point on my puppet server to gather the certs. 

I don't know how to assign my puppet manifest to a Foreman hostgroup. I am not the person that installed the puppet server / foreman node so I am quite helpless with the product.

If you have any suggestion please let me know. 
Thank you for your time

**Comment by pcfens** [comment]
If I remember correctly, Foreman only allows you to assign classes (with parameters) to hosts. You'll need to create a new profile class (assuming you're using [roles and profiles](http://www.craigdunn.org/2012/05/239/)) that you can assign to the nodes within Foreman.

Sorry I can't help more - it's been a long time since I've managed anything puppet using Foreman.
