### ISSUE TITLE
Adding output TLS feature

### ISSUE THREAD

**Issue by gsmember** [pcfens/puppet-filebeat#5]
Hello and thanks for your great module!

What I am missing is the possibility to easily set the TLS ressources.

Example:

``` ruby
outputs => {
    'logstash' => {
        'hosts' => [
            'host:5044',
        ],
        'tls' => {
            'certificate_authorities' => [
                'puppet:///modules/beats/ssl.ca',
                'puppet:///modules/beats/ssl2.ca',
            ],
            'certificate' => 'puppet:///modules/beats/ssl.crt',
            'certificate_key' => 'puppet:///modules/beats/ssl.key',
        },
    },
},
```

Thanks!

**Comment by pcfens** [comment]
I really like this idea, though it will probably take a little bit to implement.

Since I'm converting the hash to yaml (it seemed like an easier way to support a lot of nested options, and it makes the puppet code mirror the actual config file a bit), the values have to get looked at, and possibly modified before converting the hash to YAML. Since puppet variables are static something like this would either need to be done in the template, or by taking the hash apart and putting it back together in puppet code.

The trickiest issue to solve is how to handle multiple input types. `certificate` and `certificate_authorities` make sense as either a path or as a file provided by puppet (we can look for a protocol of `puppet://` or a path if it's managed outside the module to figure out how to act inside the module). `certificate_key` shouldn't be managed as a file with a `source` parameter like `puppet://` since it should be encrypted in your puppet repo (and use something like [hiera-eyaml](https://github.com/TomPoulton/hiera-eyaml) to provide the secret). Multiple CAs can't be done in a polished way since iterator functions aren't available pre version 4.

I may have to add some parameters outside of the existing hash, which breaks the idea of structuring the hash to match the yaml in the config file.

If anybody has extra thoughts feel free to jump in (or send a PR :smiley:)

**Comment by cdenneen** [comment]
@pcfens I like the idea you are suggesting and think that we are finally at a point that creating a major release that supports Puppet >= 4.x (for the iterator functions) is probably not unreasonable anymore.
Maybe create a final release for earlier versions with note that any versions going forward will be deprecating legacy support?

**Comment by pcfens** [comment]
Filebeat is being developed pretty actively developed right now, and I'd love to wait for things to stabilize a bit more before cutting off the still supported puppet 3.x. It's worth revisiting after the upcoming [v5](https://www.elastic.co/v5) switch.

Locally, we use the roles and profile pattern with a profile for filebeat that sets up certificate information (using file resources) in addition to setting up the filebeat outputs. Using file resources also allows us to switch back and forth between encrypted and plain text backends depending on the data. Once I have the time to write something equally versatile in the module (or a PR comes along), I'd be more than happy to add it to the module.

**Comment by cdenneen** [comment]
Anyway you could provide a wiki write up here of the filebeat role/profile
file resources you mentioned? Could be of great interest until v5 stack
becomes available?

**Comment by pcfens** [comment]
I added a [very short example](https://github.com/pcfens/puppet-filebeat/wiki/Managing-Certificates) to the wiki - hopefully that helps.
