### ISSUE TITLE
puppet-filebeat 0.8.0 breaks backward compatibility for filebeat 1.x

### ISSUE THREAD

**Issue by elconas** [pcfens/puppet-filebeat#64]
Pre-0.8.0 the module always assumes a major version of 1 (not really a parameter, but the manifest always creates a 1.x compatible configfile).

In 0.8.0 the module assumes $major_version of 5 if own fact $::filebeat_version can not be found. However $::filebeat_version needs a installed filebeat client to work, but this is installed as part of the inclusion. This leads to the error when updating the module (minor version update) without addin parameters:

* 1st run:
  * fact $::filebeat_version is empty as no package is installed yet
  * run filebeat module which installs filebeat package (from our mirror (which is 1.x)) and a filebeat 5.0 config file (major_version of 5 assumed)
  * start of filebeat client failes (config file incompatible ```output.logstash ...```)

* 2nd run:
  * fact $::filebeat_version is 1.x as package is installed
  * run filebeat which installs and a filebeat 1.0 config file
  * start of filebeat client ok

Fix: 
Assume default of major_version 1 to maintain backward compatibility.

**Comment by pcfens** [comment]
I'd suggest setting `major_version` to 1 rather than changing the defaults. There really isn't a perfect way to handle 2 different settings templates within a single module, so one group had their use case not fall within the defaults. Once we get to 1.0 of the module I'll make a point to maintain backwards compatibility.

If you're planning on doing much with filebeat 5, you should probably move on to version 0.8.6 of the module (it has some important fixes in the template).
