### ISSUE TITLE
filebeat::config called when no config_template set

### ISSUE THREAD

**Issue by cdenneen** [pcfens/puppet-filebeat#83]
So using manifest like this:
```
class {'filebeat':
  download_url => "https://artifacts.elastic.co/downloads/beats/filebeat/filebeat-5.1.1-windows-x86_64.zip",
}
```
Returns the following error with validate_cmd:
Trying to update the filebeats.yml with contents of template filebeat5.yml.erb.

```
Error: Execution of '"c:\Program Files\Filebeat\filebeat.exe" -N -configtest -c "C:/Program Files/Filebeat/filebeat.yml20170125-2496-86inoa"' returned 1: 2017/01/25 22:07:56 No paths given. What files do you want me to watch?
Error: /Stage[main]/Filebeat::Config/File[filebeat.yml]/content: change from {md5}73792f0b07e3e1bfc10007175bf43a1d to {md5}83f39c18a09cd309b1949c6e9ab1bf7f failed: Execution of '"c:\Program Files\Filebeat\filebeat.exe" -N -configtest -c "C:/Program Files/Filebeat/filebeat.yml20170125-2496-86inoa"' returned 1: 2017/01/25 22:07:56 No paths given. What files do you want me to watch?
Notice: /Stage[main]/Filebeat::Service/Service[filebeat]: Dependency File[filebeat.yml] has failures: true
Warning: /Stage[main]/Filebeat::Service/Service[filebeat]: Skipping because of failed dependencies
Notice: /Stage[main]/Filebeat/Anchor[filebeat::end]: Dependency File[filebeat.yml] has failures: true
Warning: /Stage[main]/Filebeat/Anchor[filebeat::end]: Skipping because of failed dependencies
```

Guessing we need a Windows default config to ship with?

**Comment by pcfens** [comment]
Using something like `include ::filebeat` on a *nix system will  get the same error since there aren't any default prospectors or outputs defined.

I think it's a matter of expected behavior - should an end user expect the the vendor packaged configuration be used (possibly without looking at it), or should it error because when an incomplete configuration is provided?

**Comment by cdenneen** [comment]
Yes windows or unix the problem happens which is why I added the condition around both file resources for `filebeat.yml`.
I think it would be useful to allow the software to be installed without defining prospectors.
Basically this would allow for default configuration of making sure filebeats is installed as "base" configuration and allow application specific configs once their apps (IIS, ES, etc) are installed to configure the prospectors as required.

Maybe alternative is to ship the default filebeat1.yml.erb and filebeat5.yml.erb with a prospector for the filebeat logfile?

**Comment by pcfens** [comment]
I'd rather keep all of the prospectors in one place (rather than some in conf.d/ and some in the configuration file). Since default value of `purge_conf_dir` is true, I don't think that we should start inserting prospectors without the end user declaring them.

If you want to install filebeat before there's an application ready for it, you might consider explicitly creating a prospector that watches the filebeat log file as part of your class declaration. Does something like that work for your use case?

**Comment by cdenneen** [comment]
I can do that.

My only issue with that is by default most contrib modules will work as
include ::module. (apache, nginx, postgresql, mysql, mongo, elasticsearch,
logstash, etc).
Now logstash for example won't run until a config is defined but it will
complete the install successfully.
I don't think it's unreasonable to include a module that will install any
of these applications. Doesn't mean they've been configured to run
Wordpress or any other "app". They are just applying their core
functionality. Doesn't mean they are enabled or running, just present.

Why not update the erb with a condition that if no prospectors configured
it appends even empty one to the base config. As soon as someone configures
their own, it's gone. Or provide a dummy erb to be used if no prospectors
provided if the condition in existing erb's isn't something you feel
comfortable with.

**Comment by cdenneen** [comment]
Disabling the config validation is useful here. Closing ticket.
